### ISSUE TITLE
Only able to connect Localhost

### ISSUE THREAD

**Issue by luigonsec** [chameleonbr/node-red-contrib-redis#35]
Hi guys!

I am facing a rare problem with the node-red-contrib-redis module. No matter how I configure the server, it always sends the commands to localhost. 

I attach pictures of how I am configuring the node, maybe that is not the way to do it.

<img width="509" alt="Captura de pantalla 2020-07-03 a las 14 27 25" src="https://user-images.githubusercontent.com/6770083/86469459-b96dfc80-bd39-11ea-8fb2-2c91d225d6b5.png">

<img width="509" alt="Captura de pantalla 2020-07-03 a las 14 27 59" src="https://user-images.githubusercontent.com/6770083/86469454-b4a94880-bd39-11ea-957a-2960d48a7ed4.png">

Any idea of what could be happening?

**Comment by chameleonbr** [comment]
Object format is:

{
"host":"10.0.0.189",
"port":6379,
"db":5
}

**Comment by chameleonbr** [comment]
Now you could add connection string to Config node too...

Look the two options...

![Captura de tela_2020-07-03_17-24-08](https://user-images.githubusercontent.com/889458/86499098-98200700-bd5f-11ea-83d3-ac1ba3e1f2c8.png)

![Captura de tela_2020-07-03_17-23-02](https://user-images.githubusercontent.com/889458/86499091-92c2bc80-bd5f-11ea-8738-e6add43645df.png)

**Comment by Kristofer3127** [comment]
By default, Redis can only be accessed locally. In addition to the object format @chameleonbr, you need to edit the Redis config file, usually found at `etc/redis/redis.conf`. Find and comment out the line `bind 127.0.0.1`. Just below it, add the line `bind 0.0.0.0`. The Redis server will now listen to all incoming IP addresses, rather than only localhost. This works for me, because in my system, security access is controlled at the network level, not at the individual app level. Reference: [Baeldung: Connecting to a Remote Redis Server](https://www.baeldung.com/linux/redis-server-remote-connect)
